IBM/cloudant-python-sdk

.gitignore, tox.ini
This PR makes `tox` to generate one per env junit test report in `test-reports` sub-dir for better tests status visibility.
No report generated.
Tests run results in xml junit report.
=> Generate test runs' junit reports

.gitignore, tox.ini
Rename junit reports dir to match other sdks
junit reports saved in `test-reports` dir
junit reports saved in `junitreports` dir
=> ci: Rename junit reports dir

requirements.txt
* resolve path params by name, not by parameter ordering
* IAM Authenticator: add support for optional 'scope' property
=> Update core version to 3.2.0

requirements.txt
`ibm_cloud_sdk_core` dependency is at version 3.2.0
`ibm_cloud_sdk_core` dependency updated to 3.3.0
https://github.com/IBM/python-sdk-core/releases/tag/v3.3.0
=> Update core dependency to 3.3.0

README.md, test/examples/src/get_info_from_existing_database.py
Change var name in `get_info_from_existing_database.py` and README examples from `examples_client` to `client` for consistency with the rest of the examples.
=> docs: Update var name in get_info_from_existing_database example

requirements-dev.txt, requirements.txt
Gather dependabot PRs into one PR.
This PR has all the commits from dependabot PRs:
https://github.com/IBM/cloudant-python-sdk/pull/25 -> websocket-client
https://github.com/IBM/cloudant-python-sdk/pull/24 -> coverage (dev)
This PR bumps the dependencies to the versions mentioned in the commit messsages.
=> Dependabot cherry pick

KNOWN_ISSUES.md
Since the `headers` parameters in the request bodies must be used as `headers_` in Python to prevent collision with the request headers (that are `headers` in the Python-wrapped request), it is good to have a section about this different behavior in the KNOWN_ISSUES.
=> Add headers to KNOWN_ISSUES

.pylintrc, ibmcloudant/common.py, ibmcloudant/couchdb_session_base_service_patch.py, ibmcloudant/couchdb_session_get_authenticator_patch.py, pylint/checkers/copyright-checker.py, pylint/checkers/license-checker.py, tox.ini
Enable copyright header checks in linting
See above.
See above.
=> Enable copyright header checks in linting

source/conf.py, source/index.rst, tox.ini
Relates to: sdks/doc-generation
No python doc is available.
This PR contains changes that needed for python document generation.
To generate the document you need to call from the project root: `python3 -m tox -e docs`
The generated doc is published on GH pages, that is available from here: https://ibm.github.io/cloudant-python-sdk/
The doc publish process is not merged yet. Here you can also review it: https://github.com/IBM/cloudant-python-sdk/pull/45
This PR contains changes that needed for python doc generation.
=> Add sphinx document generation with tox

.travis.yml, tox.ini
[Python 3.9 is now released](https://www.python.org/dev/peps/pep-0596/). This PR adds it to CI.
=> Add Python 3.9 support

requirements.txt, test/unit/test_couchdb_session_auth.py
=> Refactor test_couchdb_session_auth.py to follow core change

requirements-dev.txt, tox.ini
Currently we are not getting any benefit from the `codecov` integration and  due to [a recent security incident](https://about.codecov.io/security-update/?utm_medium=email&utm_source=marketo&ajs_uid=&ajs_event=Clicked%20Email&mkt_tok=MzMyLUxWWC03NDEAAAF8dJnGkNG_ojrjdXL2M-fOtB8t5IIphrIeLMth6mxIfuhPHB7b_FDof-GXtPcIc5fc754EGZ-_sxnLPdyBwLd1yNBoppIr0iZuG9A5_FAL) we decided to remove it.
=> ci: remove codecov install and execution

requirements-dev.txt, requirements.txt
In preparation for removing the "pre-release" flag, we should stop using version ranges so that installed versions use a specific set of dependencies.
The pinned versions are from the [latest master run](https://github.com/IBM/cloudant-python-sdk/runs/3486337204):
```
py36 installed: alabaster==0.7.12,astroid==2.7.3,attrs==21.2.0,Babel==2.9.1,
backports.entry-points-selectable==1.1.0,certifi==2021.5.30,charset-normalizer==2.0.4,commonmark==0.9.1,
coverage==5.5,distlib==0.3.2,docutils==0.17.1,filelock==3.0.12,
ibm-cloud-sdk-core==3.11.3,-e git+https://github.com/IBM/cloudant-python-sdk.git@59b96e1d9940c04d284d7fa190d7a3c732832420#egg=ibmcloudant,
idna==3.2,imagesize==1.2.0,importlib-metadata==4.8.1,importlib-resources==5.2.2,iniconfig==1.1.1,
isort==5.9.3,Jinja2==3.0.1, …
```
=> build(deps): Pin dependency versions

ibmcloudant/couchdb_session_authenticator.py, test/unit/test_couchdb_session_auth.py
The future version of the core will have an `authentication_type` function. We need to update our custom Authenticator implementations to implement this.
Getting the authentication type is not possible.
The new authenticationType method makes getting the authentication type possible.
=> feat(auth): Add authentication_type to couchdb_session_authenticator

ibmcloudant/couchdb_session_token_manager.py
Use `application/json` instead of `application/x-www-form-urlencoded` for session auth.
Fixes: #206 
Uses `data` to `POST` `application/x-www-form-urlencoded` to `_session`. 
Uses `json` to `POST` `application/json` to `_session`.
=> refactor: use json instead of form for session auth

ibmcloudant/common.py, test/unit/test_common.py
Normalize `User-Agent` header to match new sdks specs.
An example:
```
cloudant-python-sdk/0.0.43 (python.version=3.9.7; python.vendor=CPython; os.name=Darwin; os.version=20.6.0; os.arch=x86_64; lang=python;)
```
On 64 chars:
```
cloudant-python-sdk/0.0.43 (python.version=3.9.7; python.vendo
```
=> refactor: modify User-Agent header

test/examples/src/model_vs_dict/put_ddoc_class.py, test/examples/src/model_vs_dict/put_ddoc_dict.py, test/examples/src/model_vs_dict/put_ddoc_invalid.py
Fixes: <! -- link to issue -->
=> Add license headers to the model_vs_dict examples

tox.ini
Update docs basepython to 3.10
Docs build env is expecting Python 3.8, but the executor is using 3.10 now.
Use Python 3.10 in docs build env.
=> Update docs basepython to 3.10

.github/workflows/test.yml
Disable persisting the actions token
`persist-credentials: true` the default for checkout action
`persist-credentials: false`
The actions don't need to run any other `git` commands.
=> Disable persisting the actions token

test/examples/output/get_info_from_existing_database.txt, test/examples/src/get_info_from_existing_database.py
Update get_info examples to remove refs to deprecated `examples.cloudant.com`
=> docs: update get_info examples

.github/workflows/test.yml
Adds python 3.11 to test matrix
Fixes: #348 
=> ci: add python 3.11 to test matrix

.github/workflows/static.yml
Use GHA to deploy to pages.
Classic pages deployment.
GitHub Actions pages deployment.
The classic deployment no longer supports symlinks, changing to actions will hopefully avoid the need to rework the way we link latest to the most recent tagged version.
=> ci: pydoc pages deployment

ibmcloudant/version.py, setup.py
This reverts commit fc132b3a28898b6d00a83af86f8d2eb4e93826ed.
Revert bot version mangling.
- [] Build/CI related changes
Version files are broken.
Corrected version files.
=> Revert "Update version 0.4.1 -> 0.4.1"

test/examples/src/create_db_and_doc.py, test/examples/src/delete_doc.py, test/examples/src/update_doc.py
Remove unneeded log level set from examples
Change to example code.
Some of the examples set the logging level to `CRITICAL` to suppress error logging for handled exceptions (e.g. database already exists). The `python-sdk-core` used to log these unnecessarily.
Since `ibm_cloud_sdk_core==3.5.1` the extra logging of exceptions has been corrected so this log level set is no longer necessary for examples.
=> chore: remove unneeded log level set from examples

ibmcloudant/__init__.py, ibmcloudant/features/__init__.py, ibmcloudant/features/changes_follower.py, test/examples/src/features/initialize.py, test/examples/src/features/start.py, test/examples/src/features/start_and_process.py, test/examples/src/features/start_one_off.py, test/examples/src/features/start_one_off_and_process.py, test/examples/src/features/stop.py, test/unit/features/conftest.py, test/unit/features/test_changes_follower.py
Add changes follower feature.
Users have to call `postChanges` repeatedly and handle various transient errors or disconnects.
The feature adds a helper to automatically paginate the changes feed and return the changes in an iterator. It also suppresses transient exceptions and retries (though this can be disabled).
=> feat: changes follower

.github/workflows/docs.yml, .github/workflows/test.yml
This add python 3.12 in test matrix as a prep-work to enabling official support and moves docs build test to 3.12 as well since this is going to be an actual docs builder version after support enabled.   
=> Add python 3.12 in test matrix

source/conf.py
**warning: pre-req is a new release created with a new version of the generator**
Core team switched from using `:attr` to `:param` for docstrings in doc generator, so we can remove our override.
This need to wait to sdk regeneration with new version of generator, I think.
Fixes: #572 
- [ x] Tests for the changes have been added (for bug fixes / features)
To test if it's safe to merge is a bit awkward. Basically we need new release generated with a new version …
=> fix(build): remove :attr to :param override in docstrings

pyproject.toml
A maintenance update for poetry classifiers to reflect that we support python 3.12 
=> Update poetry classifiers to add python 3.12

ibmcloudant/features/changes_follower.py, source/conf.py, test/unit/features/conftest.py, test/unit/features/test_changes_follower.py
These changes will hide the internal documentation of changes follower from our following published pydoc.
This is happening because `autodoc2_hidden_objects` list has `private` in the Sphinx conf file: https://github.com/IBM/cloudant-python-sdk/blob/ac1d64c668a58c3a90270b101a7748512b0320ff/source/conf.py#L57
Fortunately from a unit test point of view there's not such thing as private, so a simple renaming resolved the tests too.
The locally generated result can be downloaded here: 
[apidocs.zip](https://github.com/IBM/cloudant-python-sdk/files/13966338/apidocs.zip) and can be compared to our [latest published pydoc](https://ibm.github.io/cloudant-python-sdk/docs/latest/).
I also fixed the copyright year to get it automatically at every pydoc generation.
**Note: An existing issue is …
=> refactor: make non-API objects private in changes follower

.github/workflows/codeql.yml
This is a maintenance PR to add CodeQL github action to the pipeline.
=> Add CodeQL config

ibmcloudant/features/changes_follower.py, test/unit/features/conftest.py, test/unit/features/test_changes_follower.py
Tests `test_start_transient_errors_with_max_suppression_all_changes` and `test_start_transient_errors_with_suppression_all_changes` are relying on test fixtures able to process expected number of changes withing given time. That proven to be a bit optimistic in resource hungry Jenkins in kube conditions.
This change is switching to use iterator instead of a generator in follower's internal docs batch to speed up iteration.
- [] Bugfix
=> Fix follower's test_start_transient_errors_with_max_suppression_all_changes test

pyproject.toml
Update package classifier
Fixes: part of s997
`"Development Status :: 4 - Beta"`
As per the readme
>We do consider this library production-ready
`"Development Status :: 5 - Production/Stable"`
=> chore: update package classifier

pyproject.toml
Update description with keywords
Fixes: part of s1012
Package metadata update
Add additional keywords for searching.
=> chore: update keywords list

.github/workflows/docs.yml, .github/workflows/test.yml, pyproject.toml
Add python 3.13 into test matrix and remove 3.8 as minimal requirements are moving to 3.9
=> chore: bump python reqs to 3.9-3.13

pyproject.toml
Update `requests` to minimum `2.32.4`
Fixes: s1166
`requests` minimum version is `2.32.2`
`requests` minimum version is `2.32.4`
=> build(deps): requests>=2.32.4

.github/workflows/static.yml
Update versions of actions in GH pages deployment workflow
Fixes: part of s1192
Deployments fail because of end-of-life dependencies.
Deployments should work.
=> ci: docs pages deployment updates
