IBM/cloudant-python-sdk

- .travis.yml
- tox.ini
[Python 3.5 is now EoL](https://www.python.org/dev/peps/pep-0478/). This PR removes it from CI.
> Remove Python 3.5 support

- .bumpversion.cfg
Update bumpversion to serialize a PEP440 normalized version
Currently publishing produces a warning:
```
/usr/local/lib/python3.6/dist-packages/setuptools/dist.py:461: UserWarning: Normalizing '0.0.32dev1613061892598+14ebe48.6' to '0.0.32.dev1613061892598+14ebe48.6'
```
Although we produce a PEP440 normalized version in our pipeline we have a slight configuration error in `.bumpversion.cfg` that serializes it in form that is PEP440 tooling compliant, but requires normalization - this produces the warning above. Specifically we serialize it without the `.` before the dev (which is the pattern only …
> Modify bumpversion for pep440 normalized versions

- test/examples/src/update_doc.py
Fixes: <! -- link to issue -->
Add stream handling examples in note comments to update document example.
> Add streaming notes to update example file

- ibmcloudant/cloudant_base_service.py
- requirements.txt
- test/integration/test_timeout.py
- Checked all type of authenticator
Fixes: <! -- link to issue -->
Currently the default read timeout value is 60 seconds.
Extended this timeout to 2.5 minutes.
The default timeout setting ( by the core) placed almost right before the request sent out, this why I selected to mock out the send request methods.
There is a [ default request timeout](https://github.com/IBM/python-sdk-core/blob/9c8d90ac890d880373e1a0ed54d4fbead35c226c/ibm_cloud_sdk_core/base_service. …
> Add 2.5 minutes read timeout as a default timeout value

- tox.ini
Fixes: #49
Custom `common`, `version`, and `cloudant_base_service` exist in the documentation.  The user does not need to interact with these modules and they can be excluded in the docs.  
Custom modules `common`, `version`, and `cloudant_base_service` removed in docs.
> Remove custom submodules in docs

- tox.ini
This fixes the failing Travis pipelines caused by https://github.com/PyCQA/astroid/issues/1239
`pylint` uses Python 3.7. as a base.
`pylint` uses Python 3.9. as a base.
> ci(pylint): Use python3.9 for linting

- .secrets.baseline
- ibmcloudant/couchdb_session_get_authenticator_patch.py
- test/unit/test_couchdb_session_auth.py
Support a env var name alias `AUTHTYPE` for `AUTH_TYPE` to keep core's compatibility
Env var of format `SERVICE_AUTHTYPE` is ignored and error thrown on missing required variable
Env var of format `SERVICE_AUTHTYPE` accepted as a valid variable same as `SERVICE_AUTH_TYPE`
> Support alias env var AUTHTYPE

- test/unit/test_cloudant_base_validation.py
Add a test to validate that we are stripping a trailing slash on setting of service URL. The test for env file is not necessary, since it's using the same `set_service_url` function under the hood.
> Validate trailing slash stripped on setting of service URL

- test/examples/src/create_db_and_doc.py
- test/examples/src/delete_doc.py
- test/examples/src/get_info_from_existing_database.py
- test/examples/src/update_doc.py
The goal of this PR is to improve the description of `_rev`/`rev` requirements for post/put document. I also fixed the ornamentation comment lines to 72 char length because I caught those not shared the same length. I also tried to explain where `_id`/`docId` is necessary similarly to `_rev`/`rev`.
I decided to use `"""...code is here..."""` for code comments and ornamentation lines before and after the explanation plus the commented out codes because with this way maybe the eyes can catch what belongs to what. Something like this:
```python
#/ ========================================================================
"""
code is here
"""
```
I also added missing copyright headers to the examples.
**Note: An existing issue is [required](https://github.com/IBM/cloudant-python-sdk/blob/master/ …
> docs: improve description of rev requirements for post/put document

- ibmcloudant/cloudant_base_service.py
- test/unit/test_cloudant_base_validation.py
add missing operation names to path validator
**Note: An existing issue is [required](https://github.com/IBM/cloudant-java-sdk/blob/main/CONTRIBUTING.md#PRs) before opening a PR.**
Not all operations have paths validated
Validate paths additionally on
`get_document_as_mixed`
`get_document_as_related`
`get_document_as_stream`
migration path: any applications which use special paths for the above operations should use the correct operation, eg one of the `*all_docs*` methods in the case of the `_all_docs` path.
> fix: add missing operation names to path validator

- ibmcloudant/cloudant_base_service.py
- ibmcloudant/couchdb_session_authenticator.py
- ibmcloudant/couchdb_session_get_authenticator_patch.py
- ibmcloudant/couchdb_session_token_manager.py
- test/unit/test_couchdb_session_auth.py
AN authenticator `CouchDbSessionAuthenticator` throws an exception on self-signed cert even when `CLOUDANT_DISABLE_SSL` variable set to true.
There are new env var `AUTH_DISABLE_SSL` in core-sdk that allows to skip cert validation for authenticators, but `CouchDbSessionAuthenticator` doesn't support it.
Fixes: #326 
Exception on access to `_sessions` end-point for services with self-signed SSL certificate
Value of env var `DISABLE_SSL` respected for both service …
> Make couch session authenticator to support `AUTH_DISABLE_SSL` env var

- tox.ini
Tox in 4.0 switched to comma separated list in `passenv` instead of space separated https://tox.wiki/en/4.0.3/faq.html#tox-4-changed-ini-rules
That was fine for us so far since prior 4.6 tox accepted both variants, but now it was mitigated, so we need to update our `tox.ini` to let tox bump pass
> fix: switch to comma separated passenv in tox config

- .gitignore
- requirements-dev.txt
- requirements-docs.txt
- source/conf.py
- source/index.rst
- tox.ini
We have markdown in docstrings of our generated modules. This causes issues with sphinx autodoc parser.
- Switch to autodoc2 and myst to properly parse markdown.
- Patch invalid markdown before parsing.
- Switch to "Read the Docs" theme and normalize TOC for better presentation.
Fixes: #78 
> Parse docstrings as markdown

- requirements-docs.txt
Fixes https://github.com/IBM/cloudant-python-sdk/issues/386 and compatibility issue between the 2 dependencies.
I have tested this with `python3 -m tox -e docs` as well as with running `scripts/pydoc/publish-doc.sh` (except for the push to the gh-pages branch), and everything seemed to work well.
> build(deps-docs): bump Sphinx from 5.3.0 to 6.2.1 and myst-parser from 1.0.0 to 2.0.0

- .github/workflows/docs.yml
To ensure we have docs builder working correctly for release add github action that'd run it on pull requests against `main`.
We don't care for result's correctness or compassing for `gh-pages` content, only that builder itself can be run successfully. 
> ci: add github action to test docs builder

- requirements-docs.txt
Apparently autodoc2 dep asteroid version 3 breaks the plugin and it was installed implicitly to >= 3 since it hasn't been pined in autodoc2 deps.
This PR pins asteroid to current 2.x version for time been to allow docs to be build. 
> fix(docs): pin asteroid lib to 2.x to fix autodoc2 analyzer

- test/unit/features/test_changes_follower.py
In follower's test for no suppression run we expect exception to be reported immediately, but ofc it takes some time to start follower and do the request, so we gave the test 100ms slack for the report time. Apparently this is not enough on busy Jenkins and an actual delay can approach 160-200ms
This PR bumps the slack to 300ms just to be on a safe side, as there is no good way to determine if there really were no suppression in follower, but 300ms is still good enough to assume that.
> Bump allowed runtime slack in follower's tests

- test/unit/features/conftest.py
- test/unit/features/test_changes_follower.py
Tweak follower's runner logic in followers test fixtures to address the issue when follower fails to return final count on constrained Jenkins servers.
Fixes: #584 
Periodically we are failing counter condition on tests with timeout when we are stopping the follower before it finish processing all the changes. 
Instead of waiting for looper to stop and return final coutner we push all updates into queue and then drain it from main loop after thread joined or …
> fix(test): Drain counter queue in follower's runner

- ibmcloudant/features/changes_follower.py
- test/examples/src/create_db_and_doc.py
- test/examples/src/delete_doc.py
- test/examples/src/update_doc.py
The `code` attribute of `ApiException` was recently deprecated in `python-sdk-core`.
This work replaces `code` with the new `status_code` attribute.
Python sdk core PR: https://github.com/IBM/python-sdk-core/pull/185 
Fixes: s889
> refactor: replace ApiException 'code' with 'status_code'

- pyproject.toml
Constrain requests 
* `>=2.32.0` for n CVE-2024-35195 fix.
* `<2.32.3` to avoid default certificate loading regression.
Fixes: #658
Dependency change
Regression loading default certificates with requests `2.32.3` prevents validating certifcate paths (and hence connecting).
Constrain requests to working versions.
This is temporary see also:
* #659
* https://github.com/IBM/python-sdk-core/pull/194
* https://github.com/psf/requests/issues/6730
> build(deps): requests between >=2.32.0,<2.32.3

- pyproject.toml
Restore the `requests` dependency range now that https://github.com/IBM/python-sdk-core/releases/tag/v3.20.2 is available.
Related to #660 and #676
Dependency update.
`requests` dependency is pinned to a small range avoiding the broken `2.32.3` version.
Since the core now has a workaround for the broken behaviour in `2.32.3` we can relax the range again `requests>=2.32.2,<3.0.0`
> build(deps): `requests>=2.32.2,<3.0.0`

- ibmcloudant/__init__.py
- ibmcloudant/cloudant_base_service.py
- test/unit/test_cloudant_base_error_augment.py
Add event hook for error response augmentation
Fixes: s1004
Cloudant/CouchDB error models are handled by the core with only the `error` field being processed. Obtaining e.g. the `reason` field requires additional user code.
The error response is augmented with `errors` and `trace` properties.
This improves the way the core handles the error response and enhances the user facing exception string to include the `reason`.
The `trace` is the CouchDB request ID which …
> feat: improve error responses

- test/unit/test_cloudant_base_error_augment.py
Avoid using deprecated `stream` parameter in `responses` mocks.
Fixes: part of s1004
Warnings from tests:
```
test/unit/test_cloudant_base_error_augment.py: 19 warnings
responses/__init__.py:609: DeprecationWarning: stream argument is deprecated. Use stream parameter in request directly
```
Move the `stream` parameter out of the mock dict so it isn't spread into the mock response.
No warnings.
> test: update responses stream usage

- ibmcloudant/features/changes_follower.py
- test/unit/features/conftest.py
- test/unit/features/test_changes_follower.py
This PR attempts to stabilize CI for follower's tests.
The list of changes:
- Better debug messages that doesn't show iterator stop as an exception
- Shorter timeouts on tests for faster failing on resource starved CI runners
- Simplify and refactor test runner to do iterations on main loop and run stopper in thread as Timer
- Switch to lazy-loading generator expression in main thread of follower to avoid memory and CPU overhead in tread's buffer   
Fixes: s1060 …
> Stabilize follower tests

- ibmcloudant/features/changes_follower.py
Separate starting follower's iterator from initializing it to allow setting since prior pre-fetch.
Fixes: #728 
> Correctly set since on one off follower

- ibmcloudant/cloudant_base_service.py
- test/unit/test_cloudant_base_error_augment.py
If the `x-request-id` header is on a response use it to set the error `trace` field (in preference to `x-couch-request-id`, but still use `x-couch-request-id` if there is no `x-request-id`).
Fixes: part of s1037
The error `trace` introduced in #719 only handles CouchDB's `x-couch-request-id` header on responses.
The error `trace` also handles `x-request-id` header on responses.
> feat: set x-request-id as error trace

- ibmcloudant/features/changes_follower.py
- test/unit/features/test_changes_follower.py
Use normal feed mode for changes follower one-off `FINITE` mode.
Fixes: s1115 / i445
Currently the changes follower uses `longpoll` feed type is for both start (`LISTEN`) and `start_one_off` (`FINITE`) cases.
Switch to use the normal feed type for `start_one_off` (`FINITE`) mode to avoid waiting unnecessarily till timeout on empty feeds.
> refactor(follower): use normal feed for one-off changes

- ibmcloudant/__init__.py
- ibmcloudant/features/pagination.py
- test/examples/src/features/pagination/all_docs_pagination.py
- test/examples/src/features/pagination/design_docs_pagination.py
- test/examples/src/features/pagination/find_pagination.py
- test/examples/src/features/pagination/partition_all_docs_pagination.py
- test/examples/src/features/pagination/partition_find_pagination.py
- test/examples/src/features/pagination/partition_search_pagination.py
- test/examples/src/features/pagination/partition_view_pagination.py
- test/examples/src/features/pagination/search_pagination.py
- test/examples/src/features/pagination/view_pagination.py
- test/unit/features/conftest.py
- test/unit/features/test_pagination_base.py
- test/unit/features/test_pagination_bookmark.py
- test/unit/features/test_pagination_key.py
- test/unit/features/test_pagination_operations.py
- test/unit/features/test_pagination_option_validation.py
Add pagination feature code.
Fixes: s1180
Users have to write code their own code to paginate.
Add pagination feature that provides language native streams/iterators for pages and rows for:
* Query all documents (global & partitioned)
* Query all design documents
* Query with selector syntax (global and partitioned)
* Query a search index (global & partitioned)
* Query a MapReduce view (global & partitioned)
Making the feature available early (beta) while we …
> feat: pagination

- test/examples/src/features/pagination/all_docs_pagination.py
- test/examples/src/features/pagination/design_docs_pagination.py
- test/examples/src/features/pagination/find_pagination.py
- test/examples/src/features/pagination/partition_all_docs_pagination.py
- test/examples/src/features/pagination/partition_find_pagination.py
- test/examples/src/features/pagination/partition_search_pagination.py
- test/examples/src/features/pagination/partition_view_pagination.py
- test/examples/src/features/pagination/search_pagination.py
- test/examples/src/features/pagination/view_pagination.py
Various fixes for pagination
Fixes: s1189
The new pagination feature code (unreleased) from #819 had a few bugs.
* Example code used `get_next` instead of `has_next` in `if` check
* Correct examples to use `has_next`
> docs: correct pager has_next examples

- ibmcloudant/features/pagination.py
- test/unit/features/test_pagination_base.py
- test/unit/features/test_pagination_bookmark.py
- test/unit/features/test_pagination_operations.py
- test/unit/features/test_pagination_option_validation.py
Various fixes for pagination
Fixes: s1189
The new pagination feature code (unreleased) from #819 had a few bugs.
* Wrong error message raised for consumed vs mixed state on pager
* `key` option was allowed for view-like pagers
* `skip` option set by user was not removed from subsequent pages
* Correct `Pager` state error message strings
* Disallow `key` as an option for pagination
* Remove `skip` option from subsequent pages
* Update assertions in `Pager` state …
> Pagination fixes

- ibmcloudant/__init__.py
- ibmcloudant/cloudant_base_service.py
- ibmcloudant/couchdb_session_get_authenticator_patch.py
- test/unit/test_couchdb_session_auth.py
This PR removes support of `AUTH_DISABLE_SSL` for `CouchDbSessionAuthenticator` to keep it in line with other impl and also fixes monkey-patch for `set_disable_ssl_verification` 
Fixes: s1029
We treat settings for `DISABLE_SSL` and `AUTH_DISABLE_SSL` as a separate entries in session auth, so it is possible to have it disabled for client and not for auth and visa versa. This can get confusing, since unlike other auth session queries the same URL 
Setting for …
> fix: disable_ssl_verification impl for CouchDbSessionAuthenticator
